services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    environment:
      - NODE_ENV=development
      - PORT=3000
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/bifrost?schema=public
      - JWT_SECRET=dev_jwt_secret
      - JWT_EXPIRATION=1d
      - JWT_REFRESH_EXPIRATION=7d
    volumes:
      - ./:/app
      - /app/node_modules

  postgres:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=bifrost
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: