name: Continuous Integration

on:
  push:
    branches: [ main, development ]
  pull_request:
    branches: [ main, development ]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        run: cd backend

      - name: Verify Docker Version
        run: |
          docker --version
          docker compose version

      - name: Run Backend with Docker Compose
        working-directory: ./backend
        run: |
          docker-compose up -d
          sleep 10

      - name: Run Tests
        working-directory: ./backend
        run: npm run test

      - name: Stop and Remove Containers
        if: always()
        working-directory: ./backend
        run: docker-compose down
